name: ci

env: { CI: true }

on:
  push:
    branches:
      - main
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Build
        run: yarn build

      - name: Get channel ID
        id: get-channel-id
        run: |
          GITHUB_BRANCH=${GITHUB_REF#refs/heads/}
          CHANNEL=$([ "$GITHUB_BRANCH" == main ] && echo "staging" || echo "live")
          echo "::set-output name=id::$CHANNEL"

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MURAR8_HN_CLIENT }}"
          channelId: "${{ steps.get-channel-id.outputs.id }}"
          # repoToken: "${{ secrets.GITHUB_TOKEN }}"
          # projectId: murar8-hn-client
